general_practitioner_task:
  description: >
    Conduct research about health issues to figure out what is going on with the patient.
    Ask the patient more questions if needed to find about their current health, pain.
    Consider if an appointment with a doctor is urgently needed or the patient can rest at home.
    
    Patient's initial description about how they are now: {initial_con}
  expected_output: >
    Comprehensive message to the patient, which includes diagnoses and advices, and also whether the patient to see the doctor urgently.

clinic_appointment_maker_task:
  description: >
    Based on the pre-assessment of General practitioner, check if the patient needs to see doctor urgently, if yes, help the patient schedule an appointment with the doctor by asking politely and friendly their preferable time to visit the clinic.
  expected_output: >
    If the patient provides their time for doctor appointment, say 'thank you' and a message to tell the patient that a doctor will call to set up the appointment soon.
    Send the patient wishes.
    

