general_practitioner_task:
  description: >
    Communicate with the patient to gather complaints, symptoms and signs to determine which disease or condition the patient is dealing with.
    Patient's initial description about how they are now: {initial_con}
#    Use SpeakingTool tool in every interaction
#    But in cases of open wounds reported, before asking further questions, take a close look at them with your EyeTool, and try to interpret the wounds in rounded boxes as much as you can, like size, whether it's swelling or deep before the actual interview.
#    Conduct research about health issues to figure out what is going on with the patient.
#    Ask the patient more questions if needed to find about their current health, pain.
#    Consider if an appointment with a doctor is urgently needed or the patient can rest at home.
  expected_output: >
    You must respond with a dictionary of extracted information in the following format: ['interview_summary':  which is the detailed summary of the patient's input, 'diagnoses': which are the diagnoses based on your medical knowledge, 'doctor_checkup_needed':boolean (wheather further doctor checkup required or not)]
    The response should contain ONLY the dictionary.
    Comprehensive message to the patient, which includes diagnoses and advices, and also whether the patient to see the doctor urgently.

pose_checking_task:
  description: >
    Tell user that after 10 second a picture will captured then wait 10 seconds and use PoseCheck tool.
  expected_output: >
    True or False. True means good pose

tremor_checking_task:
  description: >
    Use TremorCheck tool to save video
  expected_output: >
    True or False. True means has tremor

appointment_scheduling_task:
  description: >
    Your task is to interact with patients to schedule their appointments efficiently. 
    You must gather all necessary details, such as the preferred date and time, 
    Use AvailableSlot tool to suggest a date and time from the returning event list
    Remember which position datetime the user choose take that position item from event_names list and input to BookSlot tool to book in google calender
    the reason for the appointment, and any specific requirements or constraints the patient may have. 
    Simultaneously, you need to ensure the appointment aligns with the healthcare provider's availability, 
    avoiding conflicts and optimizing the schedule.

    This task requires you to be empathetic, organized, and clear in your communication, 
    guiding the patient to find the best possible time while respecting their preferences.
  expected_output: >
    The result of this task should be a confirmed appointment that includes the following details:
    
    - Patient Information: Name, contact details, and any relevant identification.
    - Appointment Date and Time: Clearly specified and agreed upon.
    - Reason for Appointment: A brief note on why the patient is visiting 
      (e.g., consultation, follow-up, specific procedure).
    - Special Notes: Any additional information, such as accessibility needs, 
      interpreter requirements, or specific doctor preferences.
    - Confirmation: A final confirmation message or email sent to the patient 
      summarizing the appointment details.

    This ensures clarity and preparedness for both the patient and the healthcare provider.

personal_info_collector:
  description: >
    Run the EyeTool to extract text from some image.
  expected_output: >
    Text from the given image.

personal_info_collector_sub:
  description: >
    Run the EyeTool to turn on the camera to see the patient's id card. After 10 seconds, capture the id card.
    Based on the recently captured id card 'id-card2.png', extract text and identify names and id number of the patient.
    Ensure that the extracted text is accurate and complete as these info are important to identify the patient.
  expected_output: >
    The copied image to 'copy.png'
    A list that includes name, id number of the patient.

clinic_appointment_maker_task:
  description: >
    Based on the pre-assessment of General practitioner, check if the patient needs to see doctor urgently, if yes, help the patient schedule an appointment with the doctor by asking politely and friendly their preferable time to visit the clinic.
  expected_output: >
    If the patient provides their time for doctor appointment, say 'thank you' and a message to tell the patient that a doctor will call to set up the appointment soon.
    Send the patient wishes.
    

